//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更此檔案可能會導致不正確的行為，而且若已重新產生
//     程式碼，則會遺失變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DrugInfoDto", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.ApplicationLayer." +
        "DTO")]
    public partial class DrugInfoDto : object
    {
        
        private string DRG_ATC_CODEField;
        
        private string DRG_BARCODEField;
        
        private string DRG_BARCODE_STOCKField;
        
        private string DRG_CODEField;
        
        private string DRG_NAMEField;
        
        private string DRG_NOMENCLATUREField;
        
        private string DRG_SPECField;
        
        private System.Nullable<decimal> DRG_SPEC_QTYField;
        
        private string DRG_SPEC_UNITField;
        
        private string DRG_UNITField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DRG_ATC_CODE
        {
            get
            {
                return this.DRG_ATC_CODEField;
            }
            set
            {
                this.DRG_ATC_CODEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DRG_BARCODE
        {
            get
            {
                return this.DRG_BARCODEField;
            }
            set
            {
                this.DRG_BARCODEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DRG_BARCODE_STOCK
        {
            get
            {
                return this.DRG_BARCODE_STOCKField;
            }
            set
            {
                this.DRG_BARCODE_STOCKField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DRG_CODE
        {
            get
            {
                return this.DRG_CODEField;
            }
            set
            {
                this.DRG_CODEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DRG_NAME
        {
            get
            {
                return this.DRG_NAMEField;
            }
            set
            {
                this.DRG_NAMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DRG_NOMENCLATURE
        {
            get
            {
                return this.DRG_NOMENCLATUREField;
            }
            set
            {
                this.DRG_NOMENCLATUREField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DRG_SPEC
        {
            get
            {
                return this.DRG_SPECField;
            }
            set
            {
                this.DRG_SPECField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> DRG_SPEC_QTY
        {
            get
            {
                return this.DRG_SPEC_QTYField;
            }
            set
            {
                this.DRG_SPEC_QTYField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DRG_SPEC_UNIT
        {
            get
            {
                return this.DRG_SPEC_UNITField;
            }
            set
            {
                this.DRG_SPEC_UNITField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DRG_UNIT
        {
            get
            {
                return this.DRG_UNITField;
            }
            set
            {
                this.DRG_UNITField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
        "dlers")]
    public partial class ApplicationServiceError : object
    {
        
        private string InnerExceptionDetailField;
        
        private string MessageField;
        
        private string StackTraceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InnerExceptionDetail
        {
            get
            {
                return this.InnerExceptionDetailField;
            }
            set
            {
                this.InnerExceptionDetailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace
        {
            get
            {
                return this.StackTraceField;
            }
            set
            {
                this.StackTraceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VW_LOG_BATCH_BAG_WCFDto", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.ApplicationLayer." +
        "DTO")]
    public partial class VW_LOG_BATCH_BAG_WCFDto : object
    {
        
        private string ADC_FLAGField;
        
        private string ATTField;
        
        private string BARCODEField;
        
        private string BIRTH_DATEField;
        
        private string CHINESE_NAMEField;
        
        private string DCNM_CHART_NOField;
        
        private string DRG_NAMEField;
        
        private string DRG_NOMENCLATUREField;
        
        private string DRG_SPECField;
        
        private string DRG_UNITField;
        
        private string EMP_NAME_UDField;
        
        private string ENGLISH_DESCField;
        
        private string FEECODEField;
        
        private string FREQCODEField;
        
        private string INNER_WARNINGField;
        
        private string ISFRZField;
        
        private string LASAField;
        
        private string LOG_DATEField;
        
        private System.Nullable<int> LOG_SEQField;
        
        private string LOG_TIMEField;
        
        private string OPT_NAMEField;
        
        private string OPT_NURSE_STATIONField;
        
        private string OPT_WARDField;
        
        private string ORDERUNITField;
        
        private string PARAMETER2Field;
        
        private string PRNJOBIDField;
        
        private System.Nullable<decimal> QTYField;
        
        private string SURFACE_MARKField;
        
        private string SURFACE_SHAPEField;
        
        private string UTY_EMP_CODEField;
        
        private System.Nullable<int> WOK_CHARGE_QTYField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ADC_FLAG
        {
            get
            {
                return this.ADC_FLAGField;
            }
            set
            {
                this.ADC_FLAGField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ATT
        {
            get
            {
                return this.ATTField;
            }
            set
            {
                this.ATTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BARCODE
        {
            get
            {
                return this.BARCODEField;
            }
            set
            {
                this.BARCODEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BIRTH_DATE
        {
            get
            {
                return this.BIRTH_DATEField;
            }
            set
            {
                this.BIRTH_DATEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CHINESE_NAME
        {
            get
            {
                return this.CHINESE_NAMEField;
            }
            set
            {
                this.CHINESE_NAMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DCNM_CHART_NO
        {
            get
            {
                return this.DCNM_CHART_NOField;
            }
            set
            {
                this.DCNM_CHART_NOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DRG_NAME
        {
            get
            {
                return this.DRG_NAMEField;
            }
            set
            {
                this.DRG_NAMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DRG_NOMENCLATURE
        {
            get
            {
                return this.DRG_NOMENCLATUREField;
            }
            set
            {
                this.DRG_NOMENCLATUREField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DRG_SPEC
        {
            get
            {
                return this.DRG_SPECField;
            }
            set
            {
                this.DRG_SPECField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DRG_UNIT
        {
            get
            {
                return this.DRG_UNITField;
            }
            set
            {
                this.DRG_UNITField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMP_NAME_UD
        {
            get
            {
                return this.EMP_NAME_UDField;
            }
            set
            {
                this.EMP_NAME_UDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ENGLISH_DESC
        {
            get
            {
                return this.ENGLISH_DESCField;
            }
            set
            {
                this.ENGLISH_DESCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FEECODE
        {
            get
            {
                return this.FEECODEField;
            }
            set
            {
                this.FEECODEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FREQCODE
        {
            get
            {
                return this.FREQCODEField;
            }
            set
            {
                this.FREQCODEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string INNER_WARNING
        {
            get
            {
                return this.INNER_WARNINGField;
            }
            set
            {
                this.INNER_WARNINGField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISFRZ
        {
            get
            {
                return this.ISFRZField;
            }
            set
            {
                this.ISFRZField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LASA
        {
            get
            {
                return this.LASAField;
            }
            set
            {
                this.LASAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LOG_DATE
        {
            get
            {
                return this.LOG_DATEField;
            }
            set
            {
                this.LOG_DATEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> LOG_SEQ
        {
            get
            {
                return this.LOG_SEQField;
            }
            set
            {
                this.LOG_SEQField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LOG_TIME
        {
            get
            {
                return this.LOG_TIMEField;
            }
            set
            {
                this.LOG_TIMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OPT_NAME
        {
            get
            {
                return this.OPT_NAMEField;
            }
            set
            {
                this.OPT_NAMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OPT_NURSE_STATION
        {
            get
            {
                return this.OPT_NURSE_STATIONField;
            }
            set
            {
                this.OPT_NURSE_STATIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OPT_WARD
        {
            get
            {
                return this.OPT_WARDField;
            }
            set
            {
                this.OPT_WARDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ORDERUNIT
        {
            get
            {
                return this.ORDERUNITField;
            }
            set
            {
                this.ORDERUNITField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PARAMETER2
        {
            get
            {
                return this.PARAMETER2Field;
            }
            set
            {
                this.PARAMETER2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRNJOBID
        {
            get
            {
                return this.PRNJOBIDField;
            }
            set
            {
                this.PRNJOBIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> QTY
        {
            get
            {
                return this.QTYField;
            }
            set
            {
                this.QTYField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SURFACE_MARK
        {
            get
            {
                return this.SURFACE_MARKField;
            }
            set
            {
                this.SURFACE_MARKField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SURFACE_SHAPE
        {
            get
            {
                return this.SURFACE_SHAPEField;
            }
            set
            {
                this.SURFACE_SHAPEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UTY_EMP_CODE
        {
            get
            {
                return this.UTY_EMP_CODEField;
            }
            set
            {
                this.UTY_EMP_CODEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> WOK_CHARGE_QTY
        {
            get
            {
                return this.WOK_CHARGE_QTYField;
            }
            set
            {
                this.WOK_CHARGE_QTYField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KmughRtxMdaDto", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.ApplicationLayer." +
        "DTO")]
    public partial class KmughRtxMdaDto : ServiceReference.BaseDTOEntity
    {
        
        private string DRG_NAMEField;
        
        private string MDA_MED_CODEField;
        
        private string MNO_CHART_NOField;
        
        private decimal MNO_DATEField;
        
        private decimal MNO_NOField;
        
        private string MNO_NO_KINDField;
        
        private string PATIENT_NAMEField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DRG_NAME
        {
            get
            {
                return this.DRG_NAMEField;
            }
            set
            {
                this.DRG_NAMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MDA_MED_CODE
        {
            get
            {
                return this.MDA_MED_CODEField;
            }
            set
            {
                this.MDA_MED_CODEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MNO_CHART_NO
        {
            get
            {
                return this.MNO_CHART_NOField;
            }
            set
            {
                this.MNO_CHART_NOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MNO_DATE
        {
            get
            {
                return this.MNO_DATEField;
            }
            set
            {
                this.MNO_DATEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MNO_NO
        {
            get
            {
                return this.MNO_NOField;
            }
            set
            {
                this.MNO_NOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MNO_NO_KIND
        {
            get
            {
                return this.MNO_NO_KINDField;
            }
            set
            {
                this.MNO_NO_KINDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PATIENT_NAME
        {
            get
            {
                return this.PATIENT_NAMEField;
            }
            set
            {
                this.PATIENT_NAMEField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseDTOEntity", Namespace="http://schemas.datacontract.org/2004/07/AppFramework.ApplicationLayer.DTO")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference.KmughMED_LISTDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference.KmughRtxMdaDto))]
    public partial class BaseDTOEntity : object
    {
        
        private ServiceReference.RowState RowStatek__BackingFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<RowState>k__BackingField", IsRequired=true)]
        public ServiceReference.RowState RowStatek__BackingField
        {
            get
            {
                return this.RowStatek__BackingFieldField;
            }
            set
            {
                this.RowStatek__BackingFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KmughMED_LISTDto", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.ApplicationLayer." +
        "DTO")]
    public partial class KmughMED_LISTDto : ServiceReference.BaseDTOEntity
    {
        
        private string ATC_CODEField;
        
        private string DOSAGE_FORMField;
        
        private string DOSAGE_FORM_NAMEField;
        
        private string MED_CODEField;
        
        private string MED_NAMEField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ATC_CODE
        {
            get
            {
                return this.ATC_CODEField;
            }
            set
            {
                this.ATC_CODEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DOSAGE_FORM
        {
            get
            {
                return this.DOSAGE_FORMField;
            }
            set
            {
                this.DOSAGE_FORMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DOSAGE_FORM_NAME
        {
            get
            {
                return this.DOSAGE_FORM_NAMEField;
            }
            set
            {
                this.DOSAGE_FORM_NAMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MED_CODE
        {
            get
            {
                return this.MED_CODEField;
            }
            set
            {
                this.MED_CODEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MED_NAME
        {
            get
            {
                return this.MED_NAMEField;
            }
            set
            {
                this.MED_NAMEField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RowState", Namespace="http://schemas.datacontract.org/2004/07/AppFramework.ApplicationLayer.DTO")]
    public enum RowState : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unchanged = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Insert = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Update = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delete = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdmissionParam", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.ApplicationLayer." +
        "DTO")]
    public partial class AdmissionParam : object
    {
        
        private string NURSE_STATIONField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NURSE_STATION
        {
            get
            {
                return this.NURSE_STATIONField;
            }
            set
            {
                this.NURSE_STATIONField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DrougCodeParam", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.ApplicationLayer." +
        "DTO")]
    public partial class DrougCodeParam : object
    {
        
        private string DRG_CODEField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DRG_CODE
        {
            get
            {
                return this.DRG_CODEField;
            }
            set
            {
                this.DRG_CODEField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EMPCodeParam", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.ApplicationLayer." +
        "DTO")]
    public partial class EMPCodeParam : object
    {
        
        private string EMP_CODEField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMP_CODE
        {
            get
            {
                return this.EMP_CODEField;
            }
            set
            {
                this.EMP_CODEField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IADCMedicineCabinetWCFService")]
    public interface IADCMedicineCabinetWCFService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/GetDrugInfo", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/GetDrugInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/GetDrugInfoApplicationServiceErr" +
            "orFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<ServiceReference.DrugInfoDto[]> GetDrugInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/GetBATCH_BAG_By_BARCODE", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/GetBATCH_BAG_By_BARCODEResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/GetBATCH_BAG_By_BARCODEApplicati" +
            "onServiceErrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<ServiceReference.VW_LOG_BATCH_BAG_WCFDto[]> GetBATCH_BAG_By_BARCODEAsync(string BARCODE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/GetRTXMNO_Info_KMUGH", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/GetRTXMNO_Info_KMUGHResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/GetRTXMNO_Info_KMUGHApplicationS" +
            "erviceErrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<ServiceReference.KmughRtxMdaDto[]> GetRTXMNO_Info_KMUGHAsync(string BarCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/GetKMUGH_DI_LIST", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/GetKMUGH_DI_LISTResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/GetKMUGH_DI_LISTApplicationServi" +
            "ceErrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<ServiceReference.KmughMED_LISTDto[]> GetKMUGH_DI_LISTAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/Admission", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/AdmissionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/AdmissionApplicationServiceError" +
            "Fault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> AdmissionAsync(ServiceReference.AdmissionParam[] Param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/Station", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/StationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/StationApplicationServiceErrorFa" +
            "ult", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> StationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/MEDCABINET_Data", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/MEDCABINET_DataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/MEDCABINET_DataApplicationServic" +
            "eErrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> MEDCABINET_DataAsync(string inBarCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/MEDCABINET_Data_ByDateTimes", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/MEDCABINET_Data_ByDateTimesRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/MEDCABINET_Data_ByDateTimesAppli" +
            "cationServiceErrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> MEDCABINET_Data_ByDateTimesAsync(string inSDateTime, string inEDateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/DrugInfo", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/DrugInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/DrugInfoApplicationServiceErrorF" +
            "ault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> DrugInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/QueryDrugInfo", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/QueryDrugInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/QueryDrugInfoApplicationServiceE" +
            "rrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> QueryDrugInfoAsync(ServiceReference.DrougCodeParam[] Param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/DrugTrans", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/DrugTransResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/DrugTransApplicationServiceError" +
            "Fault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> DrugTransAsync(string StartTime, string EndTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/DrugSpecInfo", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/DrugSpecInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/DrugSpecInfoApplicationServiceEr" +
            "rorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> DrugSpecInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/QueryDrugSpecInfo", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/QueryDrugSpecInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/QueryDrugSpecInfoApplicationServ" +
            "iceErrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> QueryDrugSpecInfoAsync(ServiceReference.DrougCodeParam[] Param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/DrugSpecTrans", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/DrugSpecTransResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/DrugSpecTransApplicationServiceE" +
            "rrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> DrugSpecTransAsync(string StartTime, string EndTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/DrugImgUrl", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/DrugImgUrlResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/DrugImgUrlApplicationServiceErro" +
            "rFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> DrugImgUrlAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/QueryDrugImgUrl", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/QueryDrugImgUrlResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/QueryDrugImgUrlApplicationServic" +
            "eErrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> QueryDrugImgUrlAsync(ServiceReference.DrougCodeParam[] Param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/DrugImgUrlTrans", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/DrugImgUrlTransResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/DrugImgUrlTransApplicationServic" +
            "eErrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> DrugImgUrlTransAsync(string KEY_Start, string KEY_End);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/Pharmacist", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/PharmacistResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/PharmacistApplicationServiceErro" +
            "rFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> PharmacistAsync(ServiceReference.EMPCodeParam[] Param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/AdmissionTrans", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/AdmissionTransResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/AdmissionTransApplicationService" +
            "ErrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> AdmissionTransAsync(ServiceReference.AdmissionParam[] Param, string StartDate, string EndDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/QueryRtxmda_Data", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/QueryRtxmda_DataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/QueryRtxmda_DataApplicationServi" +
            "ceErrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> QueryRtxmda_DataAsync(string inBarCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/QueryRtxmda_Bags_Content", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/QueryRtxmda_Bags_ContentResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/QueryRtxmda_Bags_ContentApplicat" +
            "ionServiceErrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> QueryRtxmda_Bags_ContentAsync(string inBarCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/QueryRtxmda_Bags_ByChartMno", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/QueryRtxmda_Bags_ByChartMnoRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/QueryRtxmda_Bags_ByChartMnoAppli" +
            "cationServiceErrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> QueryRtxmda_Bags_ByChartMnoAsync(string mno_date, string chart_no, string mno_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/GetOpdFreezerDrugCode", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/GetOpdFreezerDrugCodeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/GetOpdFreezerDrugCodeApplication" +
            "ServiceErrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> GetOpdFreezerDrugCodeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/DrugExpDateAndLotNum", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/DrugExpDateAndLotNumResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/DrugExpDateAndLotNumApplicationS" +
            "erviceErrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> DrugExpDateAndLotNumAsync(ServiceReference.DrougCodeParam[] Param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/ADCItemsInfo", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/ADCItemsInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/ADCItemsInfoApplicationServiceEr" +
            "rorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> ADCItemsInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/ADCItemsTrans", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/ADCItemsTransResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/ADCItemsTransApplicationServiceE" +
            "rrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> ADCItemsTransAsync(string StartTime, string EndTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/OrdersView", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/OrdersViewResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/OrdersViewApplicationServiceErro" +
            "rFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> OrdersViewAsync(string pS_HOSPITAL_NO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/DrugView", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/DrugViewResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/DrugViewApplicationServiceErrorF" +
            "ault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> DrugViewAsync(string pS_HOSPITAL_NO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/CheckEMPPassWord", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/CheckEMPPassWordResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/CheckEMPPassWordApplicationServi" +
            "ceErrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> CheckEMPPassWordAsync(string EMP_CODE, string PassWord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/LogInEMPInfo", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/LogInEMPInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/LogInEMPInfoApplicationServiceEr" +
            "rorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> LogInEMPInfoAsync(string EMP_CODE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/GET_ADC_STRING_Result", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/GET_ADC_STRING_ResultResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/GET_ADC_STRING_ResultApplication" +
            "ServiceErrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> GET_ADC_STRING_ResultAsync(string WOK_ITEM, string WOK_USER_ID, string WOK_INHOSPID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/DrugReceiptDetail", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/DrugReceiptDetailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/DrugReceiptDetailApplicationServ" +
            "iceErrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> DrugReceiptDetailAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/GET_STORAGE_ESL_Result", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/GET_STORAGE_ESL_ResultResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/GET_STORAGE_ESL_ResultApplicatio" +
            "nServiceErrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> GET_STORAGE_ESL_ResultAsync(string IN_RMS_PURCHASE_NO, string IN_RMS_DRG_NO, string IN_RMS_FREE_CHARGE_FLAG, string IN_RMS_DATE, string IN_RMS_SEQ_NO, string IN_USER_ID, string IN_ESL_FLAG, string IN_ESL_DATE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/DrugIssueDetail", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/DrugIssueDetailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/DrugIssueDetailApplicationServic" +
            "eErrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> DrugIssueDetailAsync(string Inday_tx_code, string Inday_dept_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/GET_ISSURE_ESL_Result", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/GET_ISSURE_ESL_ResultResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/GET_ISSURE_ESL_ResultApplication" +
            "ServiceErrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> GET_ISSURE_ESL_ResultAsync(string IN_DAY_TX_CODE, string IN_DAY_DATE, string IN_DAY_SHEET_NO, string IN_USER_ID, string IN_ESL_FLAG, string IN_ESL_DATE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/DrugInventoryDetail", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/DrugInventoryDetailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/DrugInventoryDetailApplicationSe" +
            "rviceErrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> DrugInventoryDetailAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/DrugInventoryDetailBySTK_NO", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/DrugInventoryDetailBySTK_NORespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/DrugInventoryDetailBySTK_NOAppli" +
            "cationServiceErrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> DrugInventoryDetailBySTK_NOAsync(string STK_NO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/GetReqDetpList", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/GetReqDetpListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/GetReqDetpListApplicationService" +
            "ErrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> GetReqDetpListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/GetSTKDetpList", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/GetSTKDetpListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/GetSTKDetpListApplicationService" +
            "ErrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> GetSTKDetpListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/GetReqTypeList", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/GetReqTypeListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/GetReqTypeListApplicationService" +
            "ErrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> GetReqTypeListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/GetDrugInStockDetail", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/GetDrugInStockDetailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/GetDrugInStockDetailApplicationS" +
            "erviceErrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> GetDrugInStockDetailAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/FunSendAbnormalMSG", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/FunSendAbnormalMSGResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/FunSendAbnormalMSGApplicationSer" +
            "viceErrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> FunSendAbnormalMSGAsync(string AccountId, string PatientId, string Station, string Send_Msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/GetSubStorgeDRGList", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/GetSubStorgeDRGListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/GetSubStorgeDRGListApplicationSe" +
            "rviceErrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> GetSubStorgeDRGListAsync(string Indate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/GetSubStorgeDrgCount", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/GetSubStorgeDrgCountResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/GetSubStorgeDrgCountApplicationS" +
            "erviceErrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> GetSubStorgeDrgCountAsync(string Indate, string STATION);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/GetSubStorgeStation", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/GetSubStorgeStationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/GetSubStorgeStationApplicationSe" +
            "rviceErrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> GetSubStorgeStationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/GetSubStorgeDateCount", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/GetSubStorgeDateCountResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/GetSubStorgeDateCountApplication" +
            "ServiceErrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> GetSubStorgeDateCountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/GetQryStockADC", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/GetQryStockADCResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/GetQryStockADCApplicationService" +
            "ErrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> GetQryStockADCAsync(string KIND);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/QuerySubStorgeDrugInfo", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/QuerySubStorgeDrugInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/QuerySubStorgeDrugInfoApplicatio" +
            "nServiceErrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> QuerySubStorgeDrugInfoAsync(ServiceReference.DrougCodeParam[] Param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/GET_DRG_EXPDATE_INYEAR_INFO", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/GET_DRG_EXPDATE_INYEAR_INFORespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/GET_DRG_EXPDATE_INYEAR_INFOAppli" +
            "cationServiceErrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> GET_DRG_EXPDATE_INYEAR_INFOAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/GET_DRG_EXPDATE_INFO_ALL", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/GET_DRG_EXPDATE_INFO_ALLResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/GET_DRG_EXPDATE_INFO_ALLApplicat" +
            "ionServiceErrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> GET_DRG_EXPDATE_INFO_ALLAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/GET_ANESTHETIC_DAILY_REPORT", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/GET_ANESTHETIC_DAILY_REPORTRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/GET_ANESTHETIC_DAILY_REPORTAppli" +
            "cationServiceErrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> GET_ANESTHETIC_DAILY_REPORTAsync(string BEGIN_DATE, string END_DATE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/GET_DRG_FROZEN_STOCK_INFO", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/GET_DRG_FROZEN_STOCK_INFORespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/GET_DRG_FROZEN_STOCK_INFOApplica" +
            "tionServiceErrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> GET_DRG_FROZEN_STOCK_INFOAsync(string DRG_ROOM);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/AutoStorage_Data", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/AutoStorage_DataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/AutoStorage_DataApplicationServi" +
            "ceErrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> AutoStorage_DataAsync(string inBarCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/AutoStorage_Data_ByDateTimes", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/AutoStorage_Data_ByDateTimesResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/AutoStorage_Data_ByDateTimesAppl" +
            "icationServiceErrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> AutoStorage_Data_ByDateTimesAsync(string inSDateTime, string inEDateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/QueryRtxmda_Data_KMUGH", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/QueryRtxmda_Data_KMUGHResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/QueryRtxmda_Data_KMUGHApplicatio" +
            "nServiceErrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> QueryRtxmda_Data_KMUGHAsync(string inBarCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/QryBATCH_BAG_By_BARCODE", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/QryBATCH_BAG_By_BARCODEResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/QryBATCH_BAG_By_BARCODEApplicati" +
            "onServiceErrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> QryBATCH_BAG_By_BARCODEAsync(string inBarCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/DrugInfoTcm", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/DrugInfoTcmResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/DrugInfoTcmApplicationServiceErr" +
            "orFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> DrugInfoTcmAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADCMedicineCabinetWCFService/QueryDrugInfoTcm", ReplyAction="http://tempuri.org/IADCMedicineCabinetWCFService/QueryDrugInfoTcmResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.ApplicationServiceError), Action="http://tempuri.org/IADCMedicineCabinetWCFService/QueryDrugInfoTcmApplicationServi" +
            "ceErrorFault", Name="ApplicationServiceError", Namespace="http://schemas.datacontract.org/2004/07/KMUH.ADCMedicineCabinet.Services.ErrorHan" +
            "dlers")]
        System.Threading.Tasks.Task<string> QueryDrugInfoTcmAsync(ServiceReference.DrougCodeParam[] Param);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IADCMedicineCabinetWCFServiceChannel : ServiceReference.IADCMedicineCabinetWCFService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ADCMedicineCabinetWCFServiceClient : System.ServiceModel.ClientBase<ServiceReference.IADCMedicineCabinetWCFService>, ServiceReference.IADCMedicineCabinetWCFService
    {
        
        /// <summary>
        /// 實作此部分方法來設定服務端點。
        /// </summary>
        /// <param name="serviceEndpoint">要設定的端點</param>
        /// <param name="clientCredentials">用戶端認證</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ADCMedicineCabinetWCFServiceClient() : 
                base(ADCMedicineCabinetWCFServiceClient.GetDefaultBinding(), ADCMedicineCabinetWCFServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_BigData.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ADCMedicineCabinetWCFServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ADCMedicineCabinetWCFServiceClient.GetBindingForEndpoint(endpointConfiguration), ADCMedicineCabinetWCFServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ADCMedicineCabinetWCFServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ADCMedicineCabinetWCFServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ADCMedicineCabinetWCFServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ADCMedicineCabinetWCFServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ADCMedicineCabinetWCFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference.DrugInfoDto[]> GetDrugInfoAsync()
        {
            return base.Channel.GetDrugInfoAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference.VW_LOG_BATCH_BAG_WCFDto[]> GetBATCH_BAG_By_BARCODEAsync(string BARCODE)
        {
            return base.Channel.GetBATCH_BAG_By_BARCODEAsync(BARCODE);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.KmughRtxMdaDto[]> GetRTXMNO_Info_KMUGHAsync(string BarCode)
        {
            return base.Channel.GetRTXMNO_Info_KMUGHAsync(BarCode);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.KmughMED_LISTDto[]> GetKMUGH_DI_LISTAsync()
        {
            return base.Channel.GetKMUGH_DI_LISTAsync();
        }
        
        public System.Threading.Tasks.Task<string> AdmissionAsync(ServiceReference.AdmissionParam[] Param)
        {
            return base.Channel.AdmissionAsync(Param);
        }
        
        public System.Threading.Tasks.Task<string> StationAsync()
        {
            return base.Channel.StationAsync();
        }
        
        public System.Threading.Tasks.Task<string> MEDCABINET_DataAsync(string inBarCode)
        {
            return base.Channel.MEDCABINET_DataAsync(inBarCode);
        }
        
        public System.Threading.Tasks.Task<string> MEDCABINET_Data_ByDateTimesAsync(string inSDateTime, string inEDateTime)
        {
            return base.Channel.MEDCABINET_Data_ByDateTimesAsync(inSDateTime, inEDateTime);
        }
        
        public System.Threading.Tasks.Task<string> DrugInfoAsync()
        {
            return base.Channel.DrugInfoAsync();
        }
        
        public System.Threading.Tasks.Task<string> QueryDrugInfoAsync(ServiceReference.DrougCodeParam[] Param)
        {
            return base.Channel.QueryDrugInfoAsync(Param);
        }
        
        public System.Threading.Tasks.Task<string> DrugTransAsync(string StartTime, string EndTime)
        {
            return base.Channel.DrugTransAsync(StartTime, EndTime);
        }
        
        public System.Threading.Tasks.Task<string> DrugSpecInfoAsync()
        {
            return base.Channel.DrugSpecInfoAsync();
        }
        
        public System.Threading.Tasks.Task<string> QueryDrugSpecInfoAsync(ServiceReference.DrougCodeParam[] Param)
        {
            return base.Channel.QueryDrugSpecInfoAsync(Param);
        }
        
        public System.Threading.Tasks.Task<string> DrugSpecTransAsync(string StartTime, string EndTime)
        {
            return base.Channel.DrugSpecTransAsync(StartTime, EndTime);
        }
        
        public System.Threading.Tasks.Task<string> DrugImgUrlAsync()
        {
            return base.Channel.DrugImgUrlAsync();
        }
        
        public System.Threading.Tasks.Task<string> QueryDrugImgUrlAsync(ServiceReference.DrougCodeParam[] Param)
        {
            return base.Channel.QueryDrugImgUrlAsync(Param);
        }
        
        public System.Threading.Tasks.Task<string> DrugImgUrlTransAsync(string KEY_Start, string KEY_End)
        {
            return base.Channel.DrugImgUrlTransAsync(KEY_Start, KEY_End);
        }
        
        public System.Threading.Tasks.Task<string> PharmacistAsync(ServiceReference.EMPCodeParam[] Param)
        {
            return base.Channel.PharmacistAsync(Param);
        }
        
        public System.Threading.Tasks.Task<string> AdmissionTransAsync(ServiceReference.AdmissionParam[] Param, string StartDate, string EndDate)
        {
            return base.Channel.AdmissionTransAsync(Param, StartDate, EndDate);
        }
        
        public System.Threading.Tasks.Task<string> QueryRtxmda_DataAsync(string inBarCode)
        {
            return base.Channel.QueryRtxmda_DataAsync(inBarCode);
        }
        
        public System.Threading.Tasks.Task<string> QueryRtxmda_Bags_ContentAsync(string inBarCode)
        {
            return base.Channel.QueryRtxmda_Bags_ContentAsync(inBarCode);
        }
        
        public System.Threading.Tasks.Task<string> QueryRtxmda_Bags_ByChartMnoAsync(string mno_date, string chart_no, string mno_no)
        {
            return base.Channel.QueryRtxmda_Bags_ByChartMnoAsync(mno_date, chart_no, mno_no);
        }
        
        public System.Threading.Tasks.Task<string> GetOpdFreezerDrugCodeAsync()
        {
            return base.Channel.GetOpdFreezerDrugCodeAsync();
        }
        
        public System.Threading.Tasks.Task<string> DrugExpDateAndLotNumAsync(ServiceReference.DrougCodeParam[] Param)
        {
            return base.Channel.DrugExpDateAndLotNumAsync(Param);
        }
        
        public System.Threading.Tasks.Task<string> ADCItemsInfoAsync()
        {
            return base.Channel.ADCItemsInfoAsync();
        }
        
        public System.Threading.Tasks.Task<string> ADCItemsTransAsync(string StartTime, string EndTime)
        {
            return base.Channel.ADCItemsTransAsync(StartTime, EndTime);
        }
        
        public System.Threading.Tasks.Task<string> OrdersViewAsync(string pS_HOSPITAL_NO)
        {
            return base.Channel.OrdersViewAsync(pS_HOSPITAL_NO);
        }
        
        public System.Threading.Tasks.Task<string> DrugViewAsync(string pS_HOSPITAL_NO)
        {
            return base.Channel.DrugViewAsync(pS_HOSPITAL_NO);
        }
        
        public System.Threading.Tasks.Task<string> CheckEMPPassWordAsync(string EMP_CODE, string PassWord)
        {
            return base.Channel.CheckEMPPassWordAsync(EMP_CODE, PassWord);
        }
        
        public System.Threading.Tasks.Task<string> LogInEMPInfoAsync(string EMP_CODE)
        {
            return base.Channel.LogInEMPInfoAsync(EMP_CODE);
        }
        
        public System.Threading.Tasks.Task<string> GET_ADC_STRING_ResultAsync(string WOK_ITEM, string WOK_USER_ID, string WOK_INHOSPID)
        {
            return base.Channel.GET_ADC_STRING_ResultAsync(WOK_ITEM, WOK_USER_ID, WOK_INHOSPID);
        }
        
        public System.Threading.Tasks.Task<string> DrugReceiptDetailAsync()
        {
            return base.Channel.DrugReceiptDetailAsync();
        }
        
        public System.Threading.Tasks.Task<string> GET_STORAGE_ESL_ResultAsync(string IN_RMS_PURCHASE_NO, string IN_RMS_DRG_NO, string IN_RMS_FREE_CHARGE_FLAG, string IN_RMS_DATE, string IN_RMS_SEQ_NO, string IN_USER_ID, string IN_ESL_FLAG, string IN_ESL_DATE)
        {
            return base.Channel.GET_STORAGE_ESL_ResultAsync(IN_RMS_PURCHASE_NO, IN_RMS_DRG_NO, IN_RMS_FREE_CHARGE_FLAG, IN_RMS_DATE, IN_RMS_SEQ_NO, IN_USER_ID, IN_ESL_FLAG, IN_ESL_DATE);
        }
        
        public System.Threading.Tasks.Task<string> DrugIssueDetailAsync(string Inday_tx_code, string Inday_dept_no)
        {
            return base.Channel.DrugIssueDetailAsync(Inday_tx_code, Inday_dept_no);
        }
        
        public System.Threading.Tasks.Task<string> GET_ISSURE_ESL_ResultAsync(string IN_DAY_TX_CODE, string IN_DAY_DATE, string IN_DAY_SHEET_NO, string IN_USER_ID, string IN_ESL_FLAG, string IN_ESL_DATE)
        {
            return base.Channel.GET_ISSURE_ESL_ResultAsync(IN_DAY_TX_CODE, IN_DAY_DATE, IN_DAY_SHEET_NO, IN_USER_ID, IN_ESL_FLAG, IN_ESL_DATE);
        }
        
        public System.Threading.Tasks.Task<string> DrugInventoryDetailAsync()
        {
            return base.Channel.DrugInventoryDetailAsync();
        }
        
        public System.Threading.Tasks.Task<string> DrugInventoryDetailBySTK_NOAsync(string STK_NO)
        {
            return base.Channel.DrugInventoryDetailBySTK_NOAsync(STK_NO);
        }
        
        public System.Threading.Tasks.Task<string> GetReqDetpListAsync()
        {
            return base.Channel.GetReqDetpListAsync();
        }
        
        public System.Threading.Tasks.Task<string> GetSTKDetpListAsync()
        {
            return base.Channel.GetSTKDetpListAsync();
        }
        
        public System.Threading.Tasks.Task<string> GetReqTypeListAsync()
        {
            return base.Channel.GetReqTypeListAsync();
        }
        
        public System.Threading.Tasks.Task<string> GetDrugInStockDetailAsync()
        {
            return base.Channel.GetDrugInStockDetailAsync();
        }
        
        public System.Threading.Tasks.Task<string> FunSendAbnormalMSGAsync(string AccountId, string PatientId, string Station, string Send_Msg)
        {
            return base.Channel.FunSendAbnormalMSGAsync(AccountId, PatientId, Station, Send_Msg);
        }
        
        public System.Threading.Tasks.Task<string> GetSubStorgeDRGListAsync(string Indate)
        {
            return base.Channel.GetSubStorgeDRGListAsync(Indate);
        }
        
        public System.Threading.Tasks.Task<string> GetSubStorgeDrgCountAsync(string Indate, string STATION)
        {
            return base.Channel.GetSubStorgeDrgCountAsync(Indate, STATION);
        }
        
        public System.Threading.Tasks.Task<string> GetSubStorgeStationAsync()
        {
            return base.Channel.GetSubStorgeStationAsync();
        }
        
        public System.Threading.Tasks.Task<string> GetSubStorgeDateCountAsync()
        {
            return base.Channel.GetSubStorgeDateCountAsync();
        }
        
        public System.Threading.Tasks.Task<string> GetQryStockADCAsync(string KIND)
        {
            return base.Channel.GetQryStockADCAsync(KIND);
        }
        
        public System.Threading.Tasks.Task<string> QuerySubStorgeDrugInfoAsync(ServiceReference.DrougCodeParam[] Param)
        {
            return base.Channel.QuerySubStorgeDrugInfoAsync(Param);
        }
        
        public System.Threading.Tasks.Task<string> GET_DRG_EXPDATE_INYEAR_INFOAsync()
        {
            return base.Channel.GET_DRG_EXPDATE_INYEAR_INFOAsync();
        }
        
        public System.Threading.Tasks.Task<string> GET_DRG_EXPDATE_INFO_ALLAsync()
        {
            return base.Channel.GET_DRG_EXPDATE_INFO_ALLAsync();
        }
        
        public System.Threading.Tasks.Task<string> GET_ANESTHETIC_DAILY_REPORTAsync(string BEGIN_DATE, string END_DATE)
        {
            return base.Channel.GET_ANESTHETIC_DAILY_REPORTAsync(BEGIN_DATE, END_DATE);
        }
        
        public System.Threading.Tasks.Task<string> GET_DRG_FROZEN_STOCK_INFOAsync(string DRG_ROOM)
        {
            return base.Channel.GET_DRG_FROZEN_STOCK_INFOAsync(DRG_ROOM);
        }
        
        public System.Threading.Tasks.Task<string> AutoStorage_DataAsync(string inBarCode)
        {
            return base.Channel.AutoStorage_DataAsync(inBarCode);
        }
        
        public System.Threading.Tasks.Task<string> AutoStorage_Data_ByDateTimesAsync(string inSDateTime, string inEDateTime)
        {
            return base.Channel.AutoStorage_Data_ByDateTimesAsync(inSDateTime, inEDateTime);
        }
        
        public System.Threading.Tasks.Task<string> QueryRtxmda_Data_KMUGHAsync(string inBarCode)
        {
            return base.Channel.QueryRtxmda_Data_KMUGHAsync(inBarCode);
        }
        
        public System.Threading.Tasks.Task<string> QryBATCH_BAG_By_BARCODEAsync(string inBarCode)
        {
            return base.Channel.QryBATCH_BAG_By_BARCODEAsync(inBarCode);
        }
        
        public System.Threading.Tasks.Task<string> DrugInfoTcmAsync()
        {
            return base.Channel.DrugInfoTcmAsync();
        }
        
        public System.Threading.Tasks.Task<string> QueryDrugInfoTcmAsync(ServiceReference.DrougCodeParam[] Param)
        {
            return base.Channel.QueryDrugInfoTcmAsync(Param);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_BigData))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名為 \'{0}\' 的端點。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_BigData))
            {
                return new System.ServiceModel.EndpointAddress("https://intraap.kmugh.org.tw/WEB/ADCCabinetWCF/ADCMedicineCabinetWCFService.svc");
            }
            throw new System.InvalidOperationException(string.Format("找不到名為 \'{0}\' 的端點。", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ADCMedicineCabinetWCFServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_BigData);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ADCMedicineCabinetWCFServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_BigData);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_BigData,
        }
    }
}
